### ISSUE TITLE
[FEATURE] Missing text configuration

### ISSUE THREAD

**Issue by OverStyleFR** [ralphkb/sentinel-tickets#15]
**Describe the bug**
There is no config for editing the claim message.

**Screenshots**
![image](https://github.com/ralphkb/sentinel-tickets/assets/94577363/0f167904-dc3a-4686-b3c2-7294f030409c)

**Comment by ralphkb** [comment]
That would probably fall under the feature request section instead of a bug but I will be adding support for editing such embeds as I keep merging to my new embeds system with the newly added function.

**Comment by ralphkb** [comment]
This is now added in the latest commit, thanks for the suggestion.
