### ISSUE TITLE
[FEATURE] Enhanced DM alert

### ISSUE THREAD

**Issue by OverStyleFR** [ralphkb/sentinel-tickets#17]
Hi,

## A simple feature request that upgrade the alert DM.

![image](https://github.com/ralphkb/sentinel-tickets/assets/94577363/79188534-df13-4336-a42b-a9ad655f446c)

### When you execute the command, he send a DM message to the owner of the ticket.
If the owner is replying like this :
![image](https://github.com/ralphkb/sentinel-tickets/assets/94577363/752b500a-6cff-48d4-a768-6ba71dd79ccc)
or reply next to the bot message on the ticket : 
![image](https://github.com/ralphkb/sentinel-tickets/assets/94577363/b98adc89-d22a-4fc0-8de6-9b946af626a0)

then send a new message to confirm that the ticket is not going to be deleted.

**Comment by ralphkb** [comment]
I think what you're trying to suggest is a way for the alert command to detect if the user responded within some time and to probably edit the alert to reflect that.

Will see if I can add this in the future.

**Comment by OverStyleFR** [comment]
> I think what you're trying to suggest is a way for the alert command to detect if the user responded within some time and to probably edit the alert to reflect that.
> 
> Will see if I can add this in the future.

Yeah that's that.

**Comment by ralphkb** [comment]
This has been added now in the latest commit but in a bit of a limited way. It will only listen to 2 minutes of user reply after the alert embed is sent, that is to make sure in the long run if the command ends up being used a lot so that the collectors can expire and not cause any performance issues.
It also only works if they answer in the ticket itself, since we want their attention there and not in their DMs.

Thanks for the suggestion.

**Comment by OverStyleFR** [comment]
> This has been added now in the latest commit but in a bit of a limited way. It will only listen to 2 minutes of user reply after the alert embed is sent, that is to make sure in the long run if the command ends up being used a lot so that the collectors can expire and not cause any performance issues. It also only works if they answer in the ticket itself, since we want their attention there and not in their DMs.
> 
> Thanks for the suggestion.

Can you add a option to bypass the 2 minutes time limit ? That's can be really usefull to continue after 2 minutes

**Comment by ralphkb** [comment]
I will add a config option for it in the future probably however I would suggest against increasing that time limit, it is added for performance reasons.
