### ISSUE TITLE
Second Project

### ISSUE THREAD

**Issue by LKA1337** [ralphkb/sentinel-tickets#2]
can you maybe also start a second Project like a system bot with features like giveaway,automod,verification,welcome embed if you do this pls do it like the sentinels ticket in js 😊

**Comment by ralphkb** [comment]
Hey, while making another bot project may seem like an interesting idea I don't think I will be doing that. For now I aim to continue improving this ticket bot which is a free and open source alternative to the paid ones as I try to provide a production ready and stable bot.

I am also still learning and may work on different projects in the future, so I will not be creating another discord bot at the moment.
Thank you for your suggestion though.
