### ISSUE TITLE
[BUG] Alert command don't work anymore.

### ISSUE THREAD

**Issue by OverStyleFR** [ralphkb/sentinel-tickets#21]
Hi,

The `/alert` command don't work anymore.

When i execute them :
![image](https://github.com/ralphkb/sentinel-tickets/assets/94577363/cb89376d-f9d5-4dcf-a076-da47a02622ff)

But nothing in my dms :
![image](https://github.com/ralphkb/sentinel-tickets/assets/94577363/ed3fc6b4-9f65-45a8-be2a-7fc3fbbb1542)

Btw when the ticket is closed i received the message from the bot, so it's the command `/alert`, he has a problem.

**Comment by ralphkb** [comment]
Hello, make sure to check your configuration and keep it properly updated. The option to enable the DM on alert has been moved to the embed section of the config as seen in this previous commit. fdc73f8
