### ISSUE TITLE
Suggest

### ISSUE THREAD

**Issue by MahdiTeaR** [ralphkb/sentinel-tickets#24]
- add command /pending (@user) 
to command a ticket to one of the employees
+true/false
- add support_role_ids2 (Just see this role in the delete tickets)
- blacklist time
- Possibility to choose to add the Transcript file for the person who created the ticket

**Comment by ralphkb** [comment]
Hello, the blacklist time feature has been added now in the latest commit as an optional argument in the blacklist add command.

Regarding your other suggestions, I'm not sure what you exactly mean by them so please try to rephrase them and explain further, I will probably check again in the future. Thanks.

**Comment by MahdiTeaR** [comment]
![Screenshot 2024-04-03 204540](https://github.com/ralphkb/sentinel-tickets/assets/133818503/586c1126-bc0b-4ff8-99ca-e58d343aa2bc)
 i wana add options true and false for transcript to the someone creates ticket

**Comment by MahdiTeaR** [comment]
![Screenshot 2024-04-03 204540](https://github.com/ralphkb/sentinel-tickets/assets/133818503/bdbce834-a415-43f8-957f-7c7239cfb464)

**Comment by MahdiTeaR** [comment]
i wanna support_role_ids2 does permissions view channels and send massage in close tickets catgory (Only support_role_ids2 should be added to the colse ticket category)

**Comment by MahdiTeaR** [comment]
add cmd /locdown /unlock (Permission to send messages is obtained)

**Comment by MahdiTeaR** [comment]
all blacklist massages sended by bot in form of embed be send

**Comment by ralphkb** [comment]
> ![Screenshot 2024-04-03 204540](https://private-user-images.githubusercontent.com/133818503/319438201-586c1126-bc0b-4ff8-99ca-e58d343aa2bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyMTQ1MjksIm5iZiI6MTcxMjIxNDIyOSwicGF0aCI6Ii8xMzM4MTg1MDMvMzE5NDM4MjAxLTU4NmMxMTI2LWJjMGItNGZmOC05OWNhLWU1OGQzNDNhYTJiYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNFQwNzAzNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMDg4M2JkY2JmODE4NDMzNGYxOWVkNjQyMjBiZGVmYzkxZDkyZGNmMGE0MzExNWM4MzQ1NWNhMGRjZGExZGQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eQD_yuXoOX-g16jbLsdcFtGwMwvZa0UhBa9jukQRRTw) i wana add options true and false for transcript to the someone creates ticket

If what you mean is an option to enable/disable the transcript being sent in their DMs, it's currently a part of this config option:
```YAML
DMUserSettings:
  enabled: false # Enable or disable sending a direct message to a user once their ticket has been deleted. It would contain the transcript and an embed.
```
It's not currently possible to send the embed in their DM without the transcript, but I can add an option for this in the future.

**Comment by ralphkb** [comment]
> i wanna support_role_ids2 does permissions view channels and send massage in close tickets catgory (Only support_role_ids2 should be added to the colse ticket category)

I understand the idea but I don't think I will be adding it, it doesn't sound right for specific support team members to have permissions to chat in a ticket channel where the user cannot reply back. The support team should just reopen the ticket and then normally continue it, the reopen feature is great for such cases.

**Comment by ralphkb** [comment]
> add cmd /locdown /unlock (Permission to send messages is obtained)

This sounds more like a feature of a moderation bot and not a tickets bot, considering most tickets only have 1 user in them or a few, it would be easier to use the discord timeout feature on the individual user(s) or a lockdown feature from a moderation bot on the channel.

**Comment by ralphkb** [comment]
> all blacklist massages sended by bot in form of embed be send ![Screenshot 2024-04-03 221542](https://private-user-images.githubusercontent.com/133818503/319452598-04595fd0-d1b5-4bd6-9d8f-cbed9728b9b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyMTQ1MjksIm5iZiI6MTcxMjIxNDIyOSwicGF0aCI6Ii8xMzM4MTg1MDMvMzE5NDUyNTk4LTA0NTk1ZmQwLWQxYjUtNGJkNi05ZDhmLWNiZWQ5NzI4YjliOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNFQwNzAzNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMDdjNDAwNGM2MzAyYmIzMTVlNzc5ZWUxN2Q1YjAzYWZiNDYzNGZkODkzZDM5NzA4ZTFjOGY5NDc3MmU1ZjE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EkUSoaZlfe-Ln8J0LuwIIT5dnP3K-dZ6xnAqLeQpxSY)

Some error messages or bot messages still do not use embeds as they are simple messages but I will probably change that in the future since embeds are more customizable and fancy. Thanks for the suggestion.

**Comment by MahdiTeaR** [comment]
DMUserSettings:
  enabled: false # Enable or disable sending a direct message to a user once their ticket has been deleted. It would contain the transcript and an embed.
  - transcript : false 
  - embed: true
