### ISSUE TITLE
You need to verify to open the ticket

### ISSUE THREAD

**Issue by MahdiTeaR** [ralphkb/sentinel-tickets#27]
In order to open a ticket, a person must verify
![Screenshot 2024-04-04 005639](https://github.com/ralphkb/sentinel-tickets/assets/133818503/dd6a87af-51c3-4a8d-b671-02e134f3637f)
send to us by Oauth2 in a channel

**Comment by ralphkb** [comment]
Hello, verifying users shouldn't really be the task of a ticket bot but rather a verification bot. What you can do in that case is use a verification bot and just make sure your verification bot will end up giving the verified users a specific role to show that they are verified.

Then you can add the role ID of that verified role into this section of each category configuration:
```YAML
creatorRoles: [] # The IDs of the roles that can create tickets in this category, keep it empty to allow all roles to create tickets
```

That way, only verified users will be able to create tickets in the categories where you add this role in the `creatorRoles` config option.
Good luck!
