### ISSUE TITLE
Update embed ticket notife close and delete

### ISSUE THREAD

**Issue by MahdiTeaR** [ralphkb/sentinel-tickets#28]
![IMG_9497](https://github.com/ralphkb/sentinel-tickets/assets/133818503/7596a5c0-57ca-4d56-9937-59f08a736f19)
Add creation time and process time

**Comment by MahdiTeaR** [comment]
Ad error socde code (When an error message is received, it should be sent to the Discord error channel)

**Comment by ralphkb** [comment]
> ![IMG_9497](https://private-user-images.githubusercontent.com/133818503/320329995-7596a5c0-57ca-4d56-9937-59f08a736f19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1OTM4MDIsIm5iZiI6MTcxMjU5MzUwMiwicGF0aCI6Ii8xMzM4MTg1MDMvMzIwMzI5OTk1LTc1OTZhNWMwLTU3Y2EtNGQ1Ni05OTM3LTU5ZjA4YTczNmYxOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOFQxNjI1MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMDNhMTA1MGE3YzMzM2E2MWVlOTlhMGM2NTM3YTgwZGM3Zjk1ZWZjOTQ2Y2ZiNjEwMjQ3ZTU1MjRmYTg5NjFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KyN18Fm_ifTJtwd32DnRoUSylQQj0KM4ix1QSfL7Lng) Add creation time and process time

Hello, regarding the creation time it has been added to some logs in the latest commit and will be added in more places and maybe also in transcripts in future updates.
Might look into the process time later on too, thanks for the suggestions.
