### ISSUE TITLE
add Duration bug

### ISSUE THREAD

**Issue by MahdiTeaR** [ralphkb/sentinel-tickets#29]
![Screenshot 2024-04-08 123934](https://github.com/ralphkb/sentinel-tickets/assets/133818503/18904d7b-8161-40e0-b2f7-598894ef4acd)

**Comment by ralphkb** [comment]
Hey, this is not a bug and if you just updated your bot files, you'll have to restart it then use the `/reload` command so the newly updated blacklist command changes can be loaded. This will fix the issue.
