### ISSUE TITLE
Giveaway

### ISSUE THREAD

**Issue by LKA1337** [ralphkb/sentinel-tickets#3]
Can you maybe add a giveaway command with buttons 
and the winner of the giveaway should get a dm when he wins 

Example: 
![image](https://github.com/ralphkb/sentinel-tickets/assets/128521854/6622e5c1-0194-4f48-978e-2650c4cf5121)

will be if you can do something like this 😄

**Comment by ralphkb** [comment]
Hey, such feature would be best found in a giveaway bot and not a tickets bot. When it comes to a ticket bot, this would be counted as bloat which I do not intend to add.
Suggestions should be related to tickets functionality for me to consider adding them, thanks though.
