### ISSUE TITLE
Add Command 

### ISSUE THREAD

**Issue by MahdiTeaR** [ralphkb/sentinel-tickets#33]
- Add cmd /notive to send message to all tickets active
- Add cmd /closerequest

**Comment by ralphkb** [comment]
Hey, those suggestions were also part of your previous issue which I closed and noted down. I might consider them in the future but for now I won't be adding commands that do bulk stuff like sending a message or embed in all open tickets.

Closing a ticket with a request is also not currently how the bot works, so I might add that in the future but not for now.
Thanks for the ideas.
