### ISSUE TITLE
Close ticket

### ISSUE THREAD

**Issue by iFaraons** [ralphkb/sentinel-tickets#36]
Error creating ticket: TypeError: Cannot read properties of undefined (reading 'send')
    at /root/sentinel-tickets/events/interactionCreate.js:2068:38

help

**Comment by ralphkb** [comment]
Hello, this error is mostly caused by a missing configuration option in your config.yml file or a needed configuration that you didn't adjust yet such as the default log channel. Please double check your config file and make sure it's up to date, that should sort your issue.

**Comment by ralphkb** [comment]
Hey, hopefully the answer above helped resolve your issue.
```YAML
logs:
  default: "" # The ID of the default log channel
```
Filling this section of your config.yml file with the correct channel ID for your logs channel is the fix in that case.
Thank you for using the bot!
