### ISSUE TITLE
[BUG] Admin cant close tickets if workingHours is enabled

### ISSUE THREAD

**Issue by mrc4tt** [ralphkb/sentinel-tickets#39]
This should be a workingHours error, as Staff/Support should be able to close the ticket even if support is closed, so there is no need to wait until the next day.

If workingHours is set **enabled**

Admin cannot close the ticket at all due to working hours.
![image](https://github.com/ralphkb/sentinel-tickets/assets/5301047/a2e0ced3-0171-46f3-bf84-5f471b8e0f07)

**Comment by ralphkb** [comment]
Hey, thank you for reporting! This is now fixed in the latest commit. 😄
