### ISSUE TITLE
Feedback Feature

### ISSUE THREAD

**Issue by LKA1337** [ralphkb/sentinel-tickets#4]
Make something like if the ticket get closed/deleted the creator should also get a dm where he can select 1-5 stars when he select the stars he should also had an option to add notes his feedback should send in a channel after he done everything 

if its possible maybe you can make the embed like this 

__INFORMATION__

Customer: 
*TICKET CREATOR*

Ticket Closed:
*TIME*

__FEEDBACK__

EVALUATION (in stars)
⭐⭐⭐⭐⭐

NOTES

**Comment by ralphkb** [comment]
Hello, I agree this can be a great addition to sentinel tickets and will consider adding it at some point when I get to it.
Thank you for your suggestion.

**Comment by ralphkb** [comment]
A new rating and feedback system has been added now, statistics about it such as total reviews and average ratings will be added soon as well.
I will be closing this issue as completed.
