### ISSUE TITLE
Feedback System

### ISSUE THREAD

**Issue by enesutku** [ralphkb/sentinel-tickets#40]
I have a feature request. After resolving and closing a support ticket, it would be advantageous to incorporate a feature prompting users to rate their experience. This feature entails the bot sending a post-ticket message to users, soliciting their rating on a scale from 1 to 5. To ensure user interaction and convenience, Discord's Select Menu feature can be utilized, allowing users to easily select their rating. 

Subsequently, the bot should process and record the feedback, forwarding it to a specified chat room dedicated to feedback review and analysis. 

I think this interactive rating system fosters user engagement and provides actionable insights for continual improvement of support services.

Thanks a lot!

**Comment by ralphkb** [comment]
Hello, this feature already exists in the bot and can be configured in the `config.yml` file. To enable it, you need to at least have either the delete DM embed or DM transcript enabled and the ratingSystem. The user will receive an embed with 5 options from 1 to 5 stars in a select menu then will be prompted with a discord modal to submit feedback after selecting the rating.
Once that is all done, the rating and feedback are sent to a channel of your choice based on your log channels configuration.
