### ISSUE TITLE
add role permision 

### ISSUE THREAD

**Issue by MahdiTeaR** [ralphkb/sentinel-tickets#43]
When we add a role to the tick and then close the ticket, the permission view of the added role can be taken into the ticket

**Comment by ralphkb** [comment]
Hey, can you provide more details about your feature request? An example would also be great. Thanks.

**Comment by ralphkb** [comment]
I see, thank you for your suggestion. This is currently not possible but will be added in a future update after I do some major changes later on, so I will note it down as an option I'll add at some point.
