### ISSUE TITLE
[Feature] Ability enable/disable logs and not just configure their respective channels.

### ISSUE THREAD

**Issue by mrc4tt** [ralphkb/sentinel-tickets#44]
From the config's POV

> This section allows you to configure the bot's channels to send different logs. Make sure to at least configure the default log channel.
> By leaving a channel empty "" the bot will fall back to the default log channel.

I had to edit to remove certain logs manually that I didn't need. **temporary**

**Comment by ralphkb** [comment]
Thanks for the suggestion, this will be added in the future.

**Comment by ralphkb** [comment]
This is now added in the latest commit. fa960f0
