### ISSUE TITLE
[Request] /closerequest for users if CloseStaffOnly is true

### ISSUE THREAD

**Issue by mrc4tt** [ralphkb/sentinel-tickets#46]
When `closeStaffOnly` is set to true, it could be an excellent idea that users can request to have the ticket closed by Staff.

For example, by using `/closerequest`, the bot will send a message to the channel the user wants the ticket channel to be closed.

**Comment by ralphkb** [comment]
Hey, could you provide more explanation about this feature request? For example:
- What do you think such an embed for a close request should look like?
- Should it ping the support roles of the ticket category so staff can be notified about this close request?

Other than that I think the embed will probably contain a close button, which staff can use to close the ticket.

**Comment by mrc4tt** [comment]
> * What do you think such an embed for a close request should look like?
For example, it could be:

USERNAME has requested to have his ticket closed.
> * Should it ping the support roles of the ticket category so staff can be notified about this close request?
It should be optional whether staff should be tagged or not.

> Other than that I think the embed will probably contain a close button, which staff can use to close the ticket.
Correct, so staff don't have to scroll to the top or from the pin. There can often be a lot of messages.

**Comment by ralphkb** [comment]
Thank you for your suggestion, this is now added in the latest commit. 3a0c578
