### ISSUE TITLE
Fallback Category

### ISSUE THREAD

**Issue by SSSXOX** [ralphkb/sentinel-tickets#47]
The option to add a fallback category so that in case the main category becomes full, channels are created in the fallback one

Example:
*After reaching the channel limit in the main category, the bot starts creating channels in the fallback one*

**Comment by ralphkb** [comment]
Thank you for the suggestion, this will be added in the future.

**Comment by ralphkb** [comment]
Hey, this is now added in the latest commit. 9b288f9
Make sure to update your configuration as well, the categoryID and closedCategoryID options in each category are now arrays instead of strings.
