### ISSUE TITLE
Channel discord with errors

### ISSUE THREAD

**Issue by SSSXOX** [ralphkb/sentinel-tickets#51]
The option to add a channel where bot errors, for example from the logs.txt file, will be sent.

Example:
*The bot receives an error and sends it to the error channel along with various additional information.*

**Comment by ralphkb** [comment]
Hey, thank you for your suggestion. I understand some setups might not have permissions for the bot to write to a logs.txt file so I'll look into adding that new option to sort this.

**Comment by ralphkb** [comment]
Hey, this is now added as a new config option in this commit: 0a4f785
