### ISSUE TITLE
rename claimed

### ISSUE THREAD

**Issue by MahdiTeaR** [ralphkb/sentinel-tickets#52]
automatically rename claimed
The ticket number should not be deleted when it is renamed
Example: Other => Other-TeaR-10

**Comment by ralphkb** [comment]
Hey, thanks for your suggestion. I already answered it here: https://github.com/ralphkb/sentinel-tickets/commit/e7a7ba69dce1083650472b50e94d5a673c9e47e4#commitcomment-141911173
