### ISSUE TITLE
Dm Message

### ISSUE THREAD

**Issue by MahdiTeaR** [ralphkb/sentinel-tickets#54]
# Send Message Allow Direct Messages
- When a user creates a ticket, a message will be sent to the person's dm, if the person's dm is closed, a message will be sent inside the ticket and the person will be told to open their dm and get out of the disabled dm mode
Or he can't send chat until he opens his tail

**Comment by ralphkb** [comment]
Hey, thank you for your suggestion however I don't think I'll be adding it based on the following reasons:

- If a user creates a ticket, they are seeking support and are aware they're making a ticket, they don't need a reminder in DMs.
- The current ephemeral reply the bot sends them in the channel where they used the panel already has a button that will redirect them to the ticket, I think this should be enough.

I think it's better not to force your users to enable their DMs for a functionality like that, thus I won't be adding this.
