### ISSUE TITLE
Update send error log 

### ISSUE THREAD

**Issue by MahdiTeaR** [ralphkb/sentinel-tickets#55]
change send message discord error log - before (error) => after (```error```)
![Screenshot 2024-05-14 115218](https://github.com/ralphkb/sentinel-tickets/assets/133818503/485966c1-14e9-4739-acbb-e108bf6932b7)

**Comment by ralphkb** [comment]
Hey, I think this idea is nice and would make the errors more easy to read and to copy. It is changed now in this commit: 3bca693
Thank you for the suggestion.
