### ISSUE TITLE
DM Messgae log 

### ISSUE THREAD

**Issue by MahdiTeaR** [ralphkb/sentinel-tickets#62]
Added dm log
Anyone who sends a message to dm bot will be sent to us

**Comment by ralphkb** [comment]
Hey, I don't think I will be adding something like this specially considering a user might just abuse it and spam the bot with messages which would lead to rate limit issues. I don't really see a point in knowing what the users are DMing the bot about also considering that the bot currently has no DM commands or such.

Thanks for the suggestion but as I just explained, I will not be adding this.
