### ISSUE TITLE
Optimization

### ISSUE THREAD

**Issue by SSSXOX** [ralphkb/sentinel-tickets#69]
Optimization the code so that actions like deleting and reopening tickets load faster, as the bot sometimes thinks a few seconds. Maybe, when it comes to deleting, it bot should deleting first and then send messages to DM and logs

**Comment by ralphkb** [comment]
Hello, I agree that this change would be great and it's done in the latest commit. 2e6688b
Though this will help in improving it, you would need a better host if you want it to be even faster since this is the most optimized it can get for now. Thank you for the suggestion.
