### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by MahdiTeaR** [ralphkb/sentinel-tickets#75]

**Comment by mrc4tt** [comment]
Instead of editing the message.

It would be a really good idea to provide details (others will probably ask the same question - in the future)

**Comment by ralphkb** [comment]
The original question was how to send a panel using select menu after the recent updates to the panels.
To answer that question, it's now integrated with the command itself so you can achieve that by using `/panel id:id layout:Menu`
You can also refer to the documentation website: https://sentineltickets.com/configuration/config/#multi-panel-settings
