### ISSUE TITLE
Ping Commnd Close req

### ISSUE THREAD

**Issue by MahdiTeaR** [ralphkb/sentinel-tickets#78]
- How to solve the ping problem?
![Screenshot 2024-07-01 094730](https://github.com/ralphkb/sentinel-tickets/assets/133818503/109efbdc-d1ec-4c6a-871b-3fafcdaf0db4)

**Comment by ralphkb** [comment]
Hey, the close request command uses the config option `ping_role_ids` of the ticket category to get the role IDs that will be pinged. Double check it for potential issues there and make sure your bot has permissions to ping the role.
