### ISSUE TITLE
Log ticket (panel)

### ISSUE THREAD

**Issue by MahdiTeaR** [ralphkb/sentinel-tickets#80]
Is it possible to separate the logs of the panels?
- panl 1 
 logchannel = x
 
 - panel 2 
  logchannel = y

**Comment by ralphkb** [comment]
Hey, this is not possible because the panels have nothing to do with the logs or ticket categories actions. The logs are separated based on the action, not the panel, which means you can separate logs based on what they do such as add, remove, priority, ticket creation, transcripts etc.
