### ISSUE TITLE
Autodelete closed ticket after X days

### ISSUE THREAD

**Issue by mrc4tt** [ralphkb/sentinel-tickets#84]
We need an automatic feature that automatically deletes the ticket if it has not been reopened by the user (must ignore staff) after X days. For example, this could be 30 days. 

Where the bot will autodelete the user's ticket channel after 30 days.

**Comment by ralphkb** [comment]
Hey, I am planning on adding this feature at some point in the future when I have enough time to implement it and test it properly. Thank you for the suggestion.

**Comment by ralphkb** [comment]
Hey, this feature is now added in the latest commit: e88492b
It works in a similar way to automatically closing tickets, but it checks when a ticket was closed to determine if it should be automatically deleted or not. The timestamp is saved when a ticket gets closed and is reset each time the ticket gets reopened, regardless of who reopened it.

Thanks for the suggestion.
