### ISSUE TITLE
add butten my ticket 

### ISSUE THREAD

**Issue by MahdiTeaR** [ralphkb/sentinel-tickets#85]
add Butten my ticket for panel 
![Screenshot 2024-08-19 021310](https://github.com/user-attachments/assets/14618929-39db-4d59-970a-b54f0edd6988)

**Comment by Dreamwxve** [comment]
feels redundant when people can just check their channel list

**Comment by ralphkb** [comment]
Hey, thanks for the suggestion but I agree with `Dreamwxve` that it's not a great idea for a ticket panel.
While I won't be adding it, I just added the context menu version of the new `/tickets` command, which is a faster way for users to just right click on their profile and execute the command to see a list of their tickets.

Added in this commit: 273509a
