### ISSUE TITLE
french config

### ISSUE THREAD

**Issue by npclmao** [ralphkb/sentinel-tickets#88]
hi buddy, is config.json fr up to date with the latest versions?

**Comment by mrc4tt** [comment]
I don't mean, it's up to date.

You can update it if you want. :-)

**Comment by ralphkb** [comment]
Hey, the French configuration is a contribution by users of the bot so it gets updated when new contributions happen. The current version is about 3 months old and given how often I update the bot and add new config options it's quite outdated yes but it can at least be used as a starting point and then you can add the new config options and translate them as you see fit.
Good luck!
