### ISSUE TITLE
error when running

### ISSUE THREAD

**Issue by Hamzaalaa1s** [ralphkb/sentinel-tickets#89]
so I runned the bot and configured in config.yml and everything and installed all required npms
![Uploading IMG_2577.jpeg…]()
 and I got this error

**Comment by mrc4tt** [comment]
Which error? I don't see anything on that screenshot you tried to upload..

**Comment by ralphkb** [comment]
Hey @Hamzaalaa1s, it seems the image you tried to upload is not loading properly so I can't see the error you're getting. Please paste the error on a website like [pastebin](https://pastebin.com/) and send the link here so I can check it out.
