### ISSUE TITLE
[BUG] Panel commands error

### ISSUE THREAD

**Issue by OverStyleFR** [ralphkb/sentinel-tickets#9]
**Describe the bug**
When i execute `/panel` the command don't work and show a error on the console.

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Fresh install of the bot
2. Configure your config files.
3. Execute /panel on discord.
4. See error on the console

**Screenshots**
![image](https://github.com/ralphkb/sentinel-tickets/assets/94577363/317293f3-067e-4424-bbac-d725669b8fde)

**Logs**
```bash
CombinedPropertyError (1)
  Received one or more errors

  input.iconURL
  | CombinedError (2)
  |   Received one or more errors
  | 
  |   1 ValidationError > s.nullish
  |   |   Expected undefined or null
  |   | 
  |   |   Received:
  |   |   | ''
  | 
  |   2 ExpectedConstraintError > s.string.url
  |   |   Invalid URL
  |   | 
  |   |   Expected: expected to match a URL
  |   | 
  |   |   Received:
  |   |   | ''

    at _ObjectValidator.handleIgnoreStrategy (/home/container/node_modules/@sapphire/shapeshift/dist/cjs/index.cjs:2019:70)
    at _ObjectValidator.handleStrategy (/home/container/node_modules/@sapphire/shapeshift/dist/cjs/index.cjs:1872:47)
    at _ObjectValidator.handle (/home/container/node_modules/@sapphire/shapeshift/dist/cjs/index.cjs:1972:17)
    at _ObjectValidator.parse (/home/container/node_modules/@sapphire/shapeshift/dist/cjs/index.cjs:939:90)
    at EmbedBuilder.setFooter (/home/container/node_modules/@discordjs/builders/dist/index.js:333:26)
    at Object.execute (/home/container/commands/Tickets/panel.js:43:8)
    at Object.execute (/home/container/events/interactionCreate.js:128:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

```

**Additional context**
The bot is installed on a Pterodactyl with nodejs v18.

There is my discord : @overstylefr or https://discord.tomv.ovh

**Comment by ralphkb** [comment]
Hello, sorry for the inconvenience regarding this issue and thank you for reporting it.
As Mirrage0 mentioned, you can add a footer_icon_url to the config for now to fix it. I am working on refactoring how embeds work in my bot and the next update should have precautions to prevent such errors while also adding more options to hopefully all the embeds in the bot.

**Comment by ralphkb** [comment]
The issue should no longer happen after the latest commits now. I started migrating to the new embeds function that I wrote, which is not only going to add default values for all embeds to prevent such issues but will also allow for way more customization options for each embed.
Not all of them are migrated yet but I will slowly be adding support to probably all of them.
This will require a lot of configuration changes so if you update, please make sure to keep your config up to date to avoid errors.

**Comment by OverStyleFR** [comment]
> The issue should no longer happen after the latest commits now. I started migrating to the new embeds function that I wrote, which is not only going to add default values for all embeds to prevent such issues but will also allow for way more customization options for each embed. Not all of them are migrated yet but I will slowly be adding support to probably all of them. This will require a lot of configuration changes so if you update, please make sure to keep your config up to date to avoid errors.

Okay i see, i have nothing with the bot.
So i can just delete and download the latest version and check if this work ?
