### ISSUE TITLE
Transcript And delete command/button

### ISSUE THREAD

**Issue by mods-hd** [ralphkb/sentinel-tickets#91]
Add button and command like

/transcript-delete 

That will transcript the ticket and when done it will auto delete

**Comment by mods-hd** [comment]
Does it save image too?

**Comment by ralphkb** [comment]
It follows your configuration preference, if you want it to save images then you need to enable `transcriptImages`.

```YAML
transcriptImages: true # Enable or disable saving images in HTML transcripts, note that this will increase the size of the transcript and the time taken to generate it
```

**Comment by mods-hd** [comment]
Oh ok thanks

**Comment by ralphkb** [comment]
You're welcome!
